apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic-prod-01
  labels:
      strimzi.io/cluster: kafka-cluster
spec:
  replicas: 2
  partitions: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: sbproducer
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: topic-prod-01
        operation: Write
      - resource:
          type: topic
          name: topic-prod-01
        operation: Create
      - resource:
          type: topic
          name: topic-prod-01
        operation: Describe